spring.application.name=project-booking

# Konekcija PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/event_booking_db
spring.datasource.username=postgres
spring.datasource.password=1946

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Mail Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fuelupshorts@gmail.com
spring.mail.password=xvxxuhupooondjsq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true